INSERT INTO dish (label, is_slow, is_quick, is_from_restaurant, is_vegan) VALUES
('Sushis', false, false, true, false),
('Pizza', false, false, true, false),
('Pizza (maison)', false, false, false, false),
('Soupe poireaux / pommes de terre', false, false, false, true),
('Tarte poireaux', false, false, false, true),
('Pâtes carbonara', false, false, false, false),
('Spaghetti bolognaise', false, false, false, false),
('Porc à la vietnamienne', true, false, false, false),
('Poulet champignons / moutarde', false, false, false, false),
('Croques monsieur', false, false, false, false),
('Apéro dînatoire', false, false, false, false),
('Tarte comté / tomates', false, false, false, true),
('Salade de riz', false, false, false, false),
('Salade de pâtes', false, false, false, false),
('Quiche lorraine', false, false, false, false),
('Poulet basquaise', true, false, false, false),
('Galettes', false, false, false, false),
('Curry patates douces, épinards et riz', true, false, false, false),
('Boulettes d''agneau, ratatouille et semoule', false, false, false, false),
('Taboulé', false, false, false, false),
('Parmigianna (aubergines)', true, false, false, true),
('Burgers', false, false, false, false),
('Tarte courgettes / feta', false, false, false, true),
('Steak haché / purée', false, false, false, false),
('Saumon et riz', false, false, false, false),
('Dos de cabillaud et riz', false, false, false, false),
('Oeufs à la coque / fromage', false, false, false, true),
('Omelette', false, false, false, true),
('Rougail saucisses', false, false, false, false);

INSERT INTO dish_month (dish_id, month_number) VALUES
(4, 9), (4, 10), (4, 11), (4, 12), (4, 1), (4, 2), (4, 3),
(5, 9), (5, 10), (5, 11), (5, 12), (5, 1), (5, 2), (5, 3);

INSERT INTO meal (plan_year, week_number, day_of_week, meal_type, dish_id) VALUES
(2026, 1, 2, 'DINNER', 1),
(date_part('year', CURRENT_DATE), EXTRACT(WEEK FROM CURRENT_DATE), 1, 'DINNER', 1),
(date_part('year', CURRENT_DATE), EXTRACT(WEEK FROM CURRENT_DATE), 2, 'DINNER', 2),
(date_part('year', CURRENT_DATE), EXTRACT(WEEK FROM CURRENT_DATE), 3, 'LUNCH', 3),
(date_part('year', CURRENT_DATE), EXTRACT(WEEK FROM CURRENT_DATE), 3, 'DINNER', 4),
(date_part('year', CURRENT_DATE), EXTRACT(WEEK FROM CURRENT_DATE), 4, 'DINNER', 5),
(date_part('year', CURRENT_DATE), EXTRACT(WEEK FROM CURRENT_DATE), 5, 'DINNER', 6),
(date_part('year', CURRENT_DATE), EXTRACT(WEEK FROM CURRENT_DATE), 6, 'LUNCH', 7),
(date_part('year', CURRENT_DATE), EXTRACT(WEEK FROM CURRENT_DATE), 6, 'DINNER', 8),
(date_part('year', CURRENT_DATE), EXTRACT(WEEK FROM CURRENT_DATE), 7, 'LUNCH', 9),
(date_part('year', CURRENT_DATE), EXTRACT(WEEK FROM CURRENT_DATE), 7, 'DINNER', 10);
