INSERT INTO dish (label, is_slow, is_quick, is_from_restaurant, is_vegan) VALUES
('Sushis', false, false, true, false),
('Pizza', false, false, true, false),
('Pizza (maison)', false, false, false, false),
('Soupe poireaux / pommes de terre', false, false, false, true),
('Tarte poireaux', false, false, false, true),
('Pâtes carbonara', false, false, false, false),
('Spaghetti bolognaise', false, false, false, false),
('Porc à la vietnamienne', true, false, false, false),
('Poulet champignons / moutarde', false, false, false, false),
('Croques monsieur', false, false, false, false),
('Apéro dînatoire', false, false, false, false),
('Tarte comté / tomates', false, false, false, true),
('Salade de riz', false, false, false, false),
('Salade de pâtes', false, false, false, false),
('Quiche lorraine', false, false, false, false),
('Poulet basquaise', true, false, false, false),
('Galettes', false, false, false, false),
('Curry patates douces, épinards et riz', true, false, false, false),
('Boulettes d''agneau, ratatouille et semoule', false, false, false, false),
('Taboulé', false, false, false, false),
('Parmigianna (aubergines)', true, false, false, true),
('Burgers', false, false, false, false),
('Tarte courgettes / feta', false, false, false, true),
('Steak haché / purée', false, false, false, false),
('Saumon et riz', false, false, false, false),
('Dos de cabillaud et riz', false, false, false, false),
('Oeufs à la coque / fromage', false, false, false, true),
('Omelette', false, false, false, true),
('Rougail saucisses', false, false, false, false);
