INSERT INTO dish (label, is_slow, is_quick, is_from_restaurant, is_vegan, is_fish) VALUES
('Dish 1', false, false, false, false, false),
('Dish 2', false, false, false, true, false),
('Dish 3', false, false, true, false, false),
('Dish 4', false, false, true, true, false),
('Dish 5', false, true, false, false, false),
('Dish 6', false, true, false, true, false),
('Dish 7', false, true, true, false, false),
('Dish 8', false, true, true, true, false),
('Dish 9', true, false, false, false, false),
('Dish 10', true, false, false, true, false),
('Dish 11', true, false, true, false, false),
('Dish 12', true, false, true, true, false),
('Dish 13', true, true, false, false, false),
('Dish 14', true, true, false, true, false),
('Dish 15', true, true, true, false, false),
('Dish 16', true, true, true, true, false);
